<?php
include("header.php");
?>



    <!-- main-area -->
    <main class="main-area fix">

        <!-- breadcrumb-area -->
        <div class="breadcrumb__area breadcrumb__bg" data-background="assets/img/bg/breadcrumb_bg.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="breadcrumb__content">
                            <h2 class="title">COATINGS - SPECIALITY LININGS</h2>
                            <nav class="breadcrumb">
                                <span property="itemListElement" typeof="ListItem">
                                    <a href="index.php">Home</a>
                                </span>
                                <span class="breadcrumb-separator">/</span>
                                <span property="itemListElement" typeof="ListItem">COATINGS - SPECIALITY LININGS</span>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- breadcrumb-area-end -->

        <!-- blog-details-area -->
        <section class="blog__details-area section-py-120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="blog__details-content">
                           <h2 class="title">COATINGS - SPECIALITY LININGS </h2>
                            <p>SATHYA OFFERS CUSTOMISED TAILOR-MADE FORMULATIONS EPM- ENGINEERED POLYMER MATRIX SERIES FOR SPECIFIC SPECIALITY COATING REQUIREMENTS MENTIONED BELOW IN DETAIL. IT IS CLASSIFIED AS HIGH-PERFORMANCE LINING (HPL) & ULTRA HIGH-PREFORMANCE LINING (UHPL) SERIES.</p>
                            <h2 class="title">A. HPL – HIGH PERFORMANCE LINING SYSTEMS :</h2>
                            <h2 class="title">SATHYA- EPM 100</h2>
                            <p>MULTI-FUNCTIONAL EPOXY WITH A UNIQUELY MODIFIED ALKYL-AMINE. IT  IS A FLEXIBLE, LOW VISCOSITY, EASY TO USE COATING SYSTEM USED ON STRUCTURAL STEEL, TANK EXTERIORS OR OTHER AREAS WHERE EXTRA CORROSION RESISTANCE IS REQUIRED THAN CONVENTIONAL INDUSTRIAL GRADE EPOXY INTERMEDIATE COATING.</p>
                            <h2 class="title">SATHYA EPM 200</h2>
                            <p>MULTI-FUNCTIONAL EPOXY WITH A UNIQUELY MODIFIED ALIPHATIC/ CYCLOALIPHATIC AMINE HARDENER. IT IS A MEDIUM VISCOSITY PRODUCT WITH OUTSTANDING ABRASION RESISTANCE, IMPACT RESISTANCE, AND FLEXIBILITY. IT CAN BE USED FOR RAIL CARS, ASH HOPPERS, SLURRY TANKS, SECONDARY CONTAINMENT, OR ANYWHERE REQUIRING FLEXIBILITY, ABRASION AND CHEMICAL RESISTANCE. IT IS DESIGNED TO BE APPLIED BY HAND OR WITH PLURAL COMPONENT SPRAY EQUIPMENT.</p>
                            <h2 class="title">SATHYA- EPM 201</h2>
                            <p>MULTI-FUNCTIONAL EPOXY WITH A UNIQUELY MODIFIED AMIDO-AMINE HARDENER. OUTSTANDING, VERSATILE AND EASY TO USE 100% SOLIDS MATERIAL. IT CAN BE USED IN MANY TYPES OF PROCESS AND DIRTY WATER, INCLUDING SALTWATER AND BRACKISH. TYPICAL APPLICATIONS INCLUDE, CIRCULATING WATER PIPE, PENSTOCK LINES, PROCESS WATER TANKS, SEWAGE TREATMENT, AND OTHER EQUIPMENT. IT CAN BE APPLIED BY BRUSH, ROLLER OR WITH CONVENTIONAL SPRAY EQUIPMENT. </p>
                            <h2 class="title">SATHYA-EPM 201 MT  </h2>
                            <p>MULTI-FUNCTIONAL EPOXY WITH A UNIQUELY MODIFIED AMIDO-AMINE HARDENER. IT IS A MOISTURE-TOLERANT VERSION OF THE EPM 201, WHICH CAN BE USED ON DAMS, OIL RIGS, STEEL OR CONCRETE STRUCTURES. IT CAN BE APPLIED UNDERWATER OR ON VERY WET SURFACES. </p>
                            <h2 class="title">SATHYA EPM F203  </h2>
                            <p>BIS-PHENOL F EPOXY WITH A UNIQUELY MODIFIED CYCLOALIPHATIC AMINE HARDENER. IS A FAST CURING BISPHENOL F EPOXY USED PRIMARILY FOR SECONDARY CONTAINMENT WHERE EXCELLENT CHEMICAL RESISTANCE TO SULFURIC AND OTHER INORGANIC ACIDS IS REQUIRED AT AMBIENT CURE TEMPERATURE.</p>
                            <h2 class="title">SATHYA EPM NEP  </h2>
                            <p>NOVOLAC EPOXY WITH A UNIQUELY MODIFIED CYCLOALIPHATIC AMINE HARDENER. IT IS A HIGH FUNCTIONALITY, 100% SOLIDS NOVOLAC MATERIAL, WHICH CAN BE APPLIED BY CONVENTIONAL AIRLESS SPRAY EQUIPMENT. IT CAN BE USED IN POWER PLANT OUTLET DUCTS, UTILITY SYSTEMS, PETROCHEMICAL AND ACID STORAGE TANKS, OR ANYWHERE REQUIRING OUTSTANDING CHEMICAL RESISTANCE IN AN EASY TO APPLY COATING SYSTEM. </p>
                            <h2 class="title">SATHYA EPM-GFNEP   </h2>
                            <p>GLASS FLAKES REINFORCED NOVOLAC EPOXY WITH A UNIQUELY MODIFIED CYCLOALIPHATIC AMINE HARDENER. IS A HIGH FUNCTIONALITY, 100% SOLIDS NOVOLAC MATERIAL, WHICH CAN BE APPLIED BY CONVENTIONAL AIRLESS SPRAY EQUIPMENT, BRUSH OR ROLLER. THIS COATING SYSTEM WAS ENGINEERED TO MINIMIZE WATER VAPOR TRANSMISSION RATES BY EMPLOYING A PROPRIETARY MIXTURE OF HIGH ASPECT RATIO, CHEMICALLY RESISTANT FLAKE GLASS. THIS PLATELET FILLER BLOCKS MICROSCOPIC PORES, SIGNIFICANTLY INCREASING THE COATINGS RESISTANCE TO COLD WALL, DISTILLED WATER, SOLVENTS, AS WELL AS STRONG ACIDS.</p>
                            <h2 class="title">SATHYA EPM- NEPFLEX  </h2>
                            <p>NOVOLAC EPOXY WITH A HIGH FUNCTIONALITY, FLEXIBLIZED AMINE CURING AGENT. IS A VERSATILE, ALL-PURPOSE EPOXY NOVOLAC LINING SYSTEM. THIS 100% SOLIDS COATING SYSTEM PROVIDES EXCELLENT CHEMICAL RESISTANCE TO A WIDE RANGE OF CHEMICALS INCLUDING CONCENTRATED SULFURIC ACID, 38% HYDROCHLORIC ACID, HOT CRUDE OIL, KEROSENE, GASOLINE, AND MANY MORE. </p>
                            <h2 class="title">SATHYA EPM-NEPHC  </h2>
                            <p>NOVOLAC EPOXY WITH A UNIQUELY MODIFIED CYCLOALIPHATIC AMINE HARDENER. IS A 100% SOLIDS, ZERO VOC, EPOXY NOVOLAC COATING SYSTEM. THIS MATERIAL WAS MADE TO RESIST MODERATE TO HIGH CONCENTRATION OF ACIDS WITH AN AMBIENT TEMPERATURE CURE. IT IS IDEAL FOR SECONDARY CONTAINMENT AND IMMERSION SERVICE AND VERY HIGH CHEMICAL RESISTANCE APPLICATIONS. </p>
                            <h2 class="title">SATHYA EPM-NEPUC</h2>
                            <p>ULTIMATE  CHEMICAL RESISTANCE VERSION OF EPM-NEPHC. DESIGNED FOR CONSTANT IMMERSION IN HIGH CONCENTRATIONS OF SULFURIC AND OTHER INORGANIC ACIDS. BLENDED NOVOLAC EPOXY WITH A UNIQUELY MODIFIED CYCLOALIPHATIC AMINE HARDENER. RECOMMENDED FOR INORGANIC ACIDS STORAGE TANKS. </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- blog-details-area-end -->

    </main>
    <!-- main-area-end -->

<?php
include("footer.php");
?>   